//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctf4e.Server.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _Layout_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Layout_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ctf4e.Server.Resources.Views.Shared._Layout.de", typeof(_Layout_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string MenuItems_Admin {
            get {
                return ResourceManager.GetString("MenuItems:Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin-Scoreboard.
        /// </summary>
        internal static string MenuItems_Admin_AdminScoreboard {
            get {
                return ResourceManager.GetString("MenuItems:Admin:AdminScoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguration.
        /// </summary>
        internal static string MenuItems_Admin_Configuration {
            get {
                return ResourceManager.GetString("MenuItems:Admin:Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppen.
        /// </summary>
        internal static string MenuItems_Admin_Groups {
            get {
                return ResourceManager.GetString("MenuItems:Admin:Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktive Praktika.
        /// </summary>
        internal static string MenuItems_Admin_LabExecutions {
            get {
                return ResourceManager.GetString("MenuItems:Admin:LabExecutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktika.
        /// </summary>
        internal static string MenuItems_Admin_Labs {
            get {
                return ResourceManager.GetString("MenuItems:Admin:Labs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminslots.
        /// </summary>
        internal static string MenuItems_Admin_Slots {
            get {
                return ResourceManager.GetString("MenuItems:Admin:Slots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer.
        /// </summary>
        internal static string MenuItems_Admin_Users {
            get {
                return ResourceManager.GetString("MenuItems:Admin:Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppe gründen.
        /// </summary>
        internal static string MenuItems_CreateGroup {
            get {
                return ResourceManager.GetString("MenuItems:CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktikumsübersicht.
        /// </summary>
        internal static string MenuItems_Dashboard {
            get {
                return ResourceManager.GetString("MenuItems:Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string MenuItems_Logout {
            get {
                return ResourceManager.GetString("MenuItems:Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoreboard.
        /// </summary>
        internal static string MenuItems_Scoreboard {
            get {
                return ResourceManager.GetString("MenuItems:Scoreboard", resourceCulture);
            }
        }
    }
}
