//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctf4e.Server.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdminLabExecutionsController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminLabExecutionsController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ctf4e.Server.Resources.Controllers.AdminLabExecutionsController", typeof(AdminLabExecutionsController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input..
        /// </summary>
        internal static string CreateLabExecutionForGroupAsync_InvalidInput {
            get {
                return ResourceManager.GetString("CreateLabExecutionForGroupAsync:InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lab execution was created successfully..
        /// </summary>
        internal static string CreateLabExecutionForGroupAsync_Success {
            get {
                return ResourceManager.GetString("CreateLabExecutionForGroupAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when creating the lab execution. Maybe there is already a lab execution for the given group? Check the log for more details..
        /// </summary>
        internal static string CreateLabExecutionForGroupAsync_UnknownError {
            get {
                return ResourceManager.GetString("CreateLabExecutionForGroupAsync:UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start lab for group #{0} ({1}). Is there already a lab execution for the given group?.
        /// </summary>
        internal static string CreateLabExecutionForSlotAsync_ErrorGroup {
            get {
                return ResourceManager.GetString("CreateLabExecutionForSlotAsync:ErrorGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input..
        /// </summary>
        internal static string CreateLabExecutionForSlotAsync_InvalidInput {
            get {
                return ResourceManager.GetString("CreateLabExecutionForSlotAsync:InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lab execution was created successfully..
        /// </summary>
        internal static string CreateLabExecutionForSlotAsync_Success {
            get {
                return ResourceManager.GetString("CreateLabExecutionForSlotAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when creating the lab execution(s). Check the log for more details..
        /// </summary>
        internal static string CreateLabExecutionForSlotAsync_UnknownError {
            get {
                return ResourceManager.GetString("CreateLabExecutionForSlotAsync:UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This lab execution does not exist..
        /// </summary>
        internal static string DeleteLabExecutionForGroupAsync_NotFound {
            get {
                return ResourceManager.GetString("DeleteLabExecutionForGroupAsync:NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lab execution was deleted successfully..
        /// </summary>
        internal static string DeleteLabExecutionForGroupAsync_Success {
            get {
                return ResourceManager.GetString("DeleteLabExecutionForGroupAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when deleting the lab execution. Check the log for more details..
        /// </summary>
        internal static string DeleteLabExecutionForGroupAsync_UnknownError {
            get {
                return ResourceManager.GetString("DeleteLabExecutionForGroupAsync:UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lab execution was deleted successfully..
        /// </summary>
        internal static string DeleteLabExecutionForSlotAsync_Success {
            get {
                return ResourceManager.GetString("DeleteLabExecutionForSlotAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when deleting the lab execution(s). Check the log for more details..
        /// </summary>
        internal static string DeleteLabExecutionForSlotAsync_UnknownError {
            get {
                return ResourceManager.GetString("DeleteLabExecutionForSlotAsync:UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input..
        /// </summary>
        internal static string EditLabExecutionAsync_InvalidInput {
            get {
                return ResourceManager.GetString("EditLabExecutionAsync:InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lab execution was updated successfully..
        /// </summary>
        internal static string EditLabExecutionAsync_Success {
            get {
                return ResourceManager.GetString("EditLabExecutionAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when updating the lab execution. Check the log for more details..
        /// </summary>
        internal static string EditLabExecutionAsync_UnknownError {
            get {
                return ResourceManager.GetString("EditLabExecutionAsync:UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lab execution specified..
        /// </summary>
        internal static string ShowEditLabExecutionFormAsync_MissingParameter {
            get {
                return ResourceManager.GetString("ShowEditLabExecutionFormAsync:MissingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This lab execution does not exist..
        /// </summary>
        internal static string ShowEditLabExecutionFormAsync_NotFound {
            get {
                return ResourceManager.GetString("ShowEditLabExecutionFormAsync:NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Editing an active lab execution may lead to changes of the &quot;passed&quot; status and shifts in the scoreboard. Exercise and flag submissions won&apos;t be deleted, even if those would not be possible under the new begin and end times..
        /// </summary>
        internal static string ShowEditLabExecutionFormAsync_Warning {
            get {
                return ResourceManager.GetString("ShowEditLabExecutionFormAsync:Warning", resourceCulture);
            }
        }
    }
}
