//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctf4e.Server.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdminScoreboardController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminScoreboardController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ctf4e.Server.Resources.Controllers.AdminScoreboardController", typeof(AdminScoreboardController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This lab does not exist..
        /// </summary>
        internal static string CallLabServerAsync_NotFound {
            get {
                return ResourceManager.GetString("CallLabServerAsync:NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exercise submission was created successfully..
        /// </summary>
        internal static string CreateExerciseSubmissionAsync_Success {
            get {
                return ResourceManager.GetString("CreateExerciseSubmissionAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while creating the exercise submission. Check the log for more details..
        /// </summary>
        internal static string CreateExerciseSubmissionAsync_UnknownError {
            get {
                return ResourceManager.GetString("CreateExerciseSubmissionAsync:UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The flag submission was created successfully..
        /// </summary>
        internal static string CreateFlagSubmissionAsync_Success {
            get {
                return ResourceManager.GetString("CreateFlagSubmissionAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while creating the flag submission. Check the log for more details..
        /// </summary>
        internal static string CreateFlagSubmissionAsync_UnknownError {
            get {
                return ResourceManager.GetString("CreateFlagSubmissionAsync:UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exercise submission was deleted successfully..
        /// </summary>
        internal static string DeleteExerciseSubmissionAsync_Success {
            get {
                return ResourceManager.GetString("DeleteExerciseSubmissionAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while deleting the exercise submission. Check the log for more details..
        /// </summary>
        internal static string DeleteExerciseSubmissionAsync_UnknownError {
            get {
                return ResourceManager.GetString("DeleteExerciseSubmissionAsync:UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exercise submissions were deleted successfully..
        /// </summary>
        internal static string DeleteExerciseSubmissionsAsync_Success {
            get {
                return ResourceManager.GetString("DeleteExerciseSubmissionsAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while deleting the exercise submissions. Check the log for more details..
        /// </summary>
        internal static string DeleteExerciseSubmissionsAsync_UnknownError {
            get {
                return ResourceManager.GetString("DeleteExerciseSubmissionsAsync:UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The flag submission was deleted successfully..
        /// </summary>
        internal static string DeleteFlagSubmissionAsync_Success {
            get {
                return ResourceManager.GetString("DeleteFlagSubmissionAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while deleting the flag submission. Check the log for more details..
        /// </summary>
        internal static string DeleteFlagSubmissionAsync_UnknownError {
            get {
                return ResourceManager.GetString("DeleteFlagSubmissionAsync:UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while generating the CSV file. Check the log for more details..
        /// </summary>
        internal static string DownloadAsCsvAsync_UnknownError {
            get {
                return ResourceManager.GetString("DownloadAsCsvAsync:UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Moodle upload has completed successfully..
        /// </summary>
        internal static string UploadToMoodleAsync_Success {
            get {
                return ResourceManager.GetString("UploadToMoodleAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while collecting and uploading the data. Check the log for more details..
        /// </summary>
        internal static string UploadToMoodleAsync_UnknownError {
            get {
                return ResourceManager.GetString("UploadToMoodleAsync:UnknownError", resourceCulture);
            }
        }
    }
}
