//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctf4e.Server.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdminSlotsController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminSlotsController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ctf4e.Server.Resources.Controllers.AdminSlotsController", typeof(AdminSlotsController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input..
        /// </summary>
        internal static string CreateSlotAsync_InvalidInput {
            get {
                return ResourceManager.GetString("CreateSlotAsync:InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The slot was created successfully..
        /// </summary>
        internal static string CreateSlotAsync_Success {
            get {
                return ResourceManager.GetString("CreateSlotAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when creating the slot. Check the log for more details..
        /// </summary>
        internal static string CreateSlotAsync_UnknownError {
            get {
                return ResourceManager.GetString("CreateSlotAsync:UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The slot must not have groups..
        /// </summary>
        internal static string DeleteSlotAsync_HasGroups {
            get {
                return ResourceManager.GetString("DeleteSlotAsync:HasGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This slot does not exist..
        /// </summary>
        internal static string DeleteSlotAsync_NotFound {
            get {
                return ResourceManager.GetString("DeleteSlotAsync:NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The slot was deleted successfully..
        /// </summary>
        internal static string DeleteSlotAsync_Success {
            get {
                return ResourceManager.GetString("DeleteSlotAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when deleting the slot. Check the log for more details..
        /// </summary>
        internal static string DeleteSlotAsync_UnknownError {
            get {
                return ResourceManager.GetString("DeleteSlotAsync:UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input..
        /// </summary>
        internal static string EditSlotAsync_InvalidInput {
            get {
                return ResourceManager.GetString("EditSlotAsync:InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The slot was updated successfully..
        /// </summary>
        internal static string EditSlotAsync_Success {
            get {
                return ResourceManager.GetString("EditSlotAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when updating the slot. Check the log for more details..
        /// </summary>
        internal static string EditSlotAsync_UnknownError {
            get {
                return ResourceManager.GetString("EditSlotAsync:UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No slot specified..
        /// </summary>
        internal static string ShowEditSlotFormAsync_MissingParameter {
            get {
                return ResourceManager.GetString("ShowEditSlotFormAsync:MissingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This slot does not exist..
        /// </summary>
        internal static string ShowEditSlotFormAsync_NotFound {
            get {
                return ResourceManager.GetString("ShowEditSlotFormAsync:NotFound", resourceCulture);
            }
        }
    }
}
