//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctf4e.Server.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuthenticationController_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthenticationController_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ctf4e.Server.Resources.Controllers.AuthenticationController.de", typeof(AuthenticationController_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Benutzer existiert nicht..
        /// </summary>
        internal static string AdminLoginAsUserAsync_NotFound {
            get {
                return ResourceManager.GetString("AdminLoginAsUserAsync:NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login als {0} erfolgreich..
        /// </summary>
        internal static string AdminLoginAsUserAsync_Success {
            get {
                return ResourceManager.GetString("AdminLoginAsUserAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Benutzer existiert nicht..
        /// </summary>
        internal static string DevLoginAsync_NotFound {
            get {
                return ResourceManager.GetString("DevLoginAsync:NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login erfolgreich..
        /// </summary>
        internal static string DevLoginAsync_Success {
            get {
                return ResourceManager.GetString("DevLoginAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mindestens ein eingegebener Code ist bereits einer Gruppe zugewiesen..
        /// </summary>
        internal static string HandleGroupSelectionAsync_CodeAlreadyAssigned {
            get {
                return ResourceManager.GetString("HandleGroupSelectionAsync:CodeAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Eingabe..
        /// </summary>
        internal static string HandleGroupSelectionAsync_InvalidInput {
            get {
                return ResourceManager.GetString("HandleGroupSelectionAsync:InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Gruppe wurde erfolgreich erstellt..
        /// </summary>
        internal static string HandleGroupSelectionAsync_Success {
            get {
                return ResourceManager.GetString("HandleGroupSelectionAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte loggen Sie sich erneut ein, um die Registrierung abzuschließen..
        /// </summary>
        internal static string HandleGroupSelectionAsync_SuccessInfo {
            get {
                return ResourceManager.GetString("HandleGroupSelectionAsync:SuccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden zu wenig Codes eingegeben. Die minimale Gruppengröße beträgt {0}..
        /// </summary>
        internal static string HandleGroupSelectionAsync_TooFewCodes {
            get {
                return ResourceManager.GetString("HandleGroupSelectionAsync:TooFewCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden zu viele Codes eingegeben. Die maximale Gruppengröße beträgt {0}..
        /// </summary>
        internal static string HandleGroupSelectionAsync_TooManyCodes {
            get {
                return ResourceManager.GetString("HandleGroupSelectionAsync:TooManyCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Fehler ist aufgetreten..
        /// </summary>
        internal static string HandleGroupSelectionAsync_UnknownError {
            get {
                return ResourceManager.GetString("HandleGroupSelectionAsync:UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzeraccount wurde erfolgreich erstellt..
        /// </summary>
        internal static string LoginMoodleAsync_AccountCreationSuccess {
            get {
                return ResourceManager.GetString("LoginMoodleAsync:AccountCreationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiger Login..
        /// </summary>
        internal static string LoginMoodleAsync_InvalidLogin {
            get {
                return ResourceManager.GetString("LoginMoodleAsync:InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login erfolgreich..
        /// </summary>
        internal static string LoginMoodleAsync_Success {
            get {
                return ResourceManager.GetString("LoginMoodleAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout erfolgreich..
        /// </summary>
        internal static string LogoutAsync_Success {
            get {
                return ResourceManager.GetString("LogoutAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Login ist nur über den Moodlekurs möglich..
        /// </summary>
        internal static string RenderAsync_MoodleOnly {
            get {
                return ResourceManager.GetString("RenderAsync:MoodleOnly", resourceCulture);
            }
        }
    }
}
