//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctf4e.LabServer.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GroupController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GroupController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ctf4e.LabServer.Resources.Controllers.GroupController", typeof(GroupController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input..
        /// </summary>
        internal static string CheckMultipleChoiceInputAsync_InvalidInput {
            get {
                return ResourceManager.GetString("CheckMultipleChoiceInputAsync:InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This solution is correct!.
        /// </summary>
        internal static string CheckMultipleChoiceInputAsync_Success {
            get {
                return ResourceManager.GetString("CheckMultipleChoiceInputAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured..
        /// </summary>
        internal static string CheckMultipleChoiceInputAsync_UnknownError {
            get {
                return ResourceManager.GetString("CheckMultipleChoiceInputAsync:UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This solution is not correct..
        /// </summary>
        internal static string CheckMultipleChoiceInputAsync_Wrong {
            get {
                return ResourceManager.GetString("CheckMultipleChoiceInputAsync:Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input..
        /// </summary>
        internal static string CheckScriptInputAsync_InvalidInput {
            get {
                return ResourceManager.GetString("CheckScriptInputAsync:InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This solution is correct!.
        /// </summary>
        internal static string CheckScriptInputAsync_Success {
            get {
                return ResourceManager.GetString("CheckScriptInputAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured..
        /// </summary>
        internal static string CheckScriptInputAsync_UnknownError {
            get {
                return ResourceManager.GetString("CheckScriptInputAsync:UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This solution is not correct..
        /// </summary>
        internal static string CheckScriptInputAsync_Wrong {
            get {
                return ResourceManager.GetString("CheckScriptInputAsync:Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input..
        /// </summary>
        internal static string CheckStringInputAsync_InvalidInput {
            get {
                return ResourceManager.GetString("CheckStringInputAsync:InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This solution is correct!.
        /// </summary>
        internal static string CheckStringInputAsync_Success {
            get {
                return ResourceManager.GetString("CheckStringInputAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured..
        /// </summary>
        internal static string CheckStringInputAsync_UnknownError {
            get {
                return ResourceManager.GetString("CheckStringInputAsync:UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This solution is not correct..
        /// </summary>
        internal static string CheckStringInputAsync_Wrong {
            get {
                return ResourceManager.GetString("CheckStringInputAsync:Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while communicating with the CTF server. See below for details..
        /// </summary>
        internal static string CtfError_Admin {
            get {
                return ResourceManager.GetString("CtfError:Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured..
        /// </summary>
        internal static string CtfError_Default {
            get {
                return ResourceManager.GetString("CtfError:Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. Error message: {0}.
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This exercise does not exist..
        /// </summary>
        internal static string MarkExerciseAsSolvedAsync_NotFound {
            get {
                return ResourceManager.GetString("MarkExerciseAsSolvedAsync:NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exercise was marked as &quot;solved&quot; successfully..
        /// </summary>
        internal static string MarkExerciseAsSolvedAsync_Success {
            get {
                return ResourceManager.GetString("MarkExerciseAsSolvedAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Check the server log for more details..
        /// </summary>
        internal static string MarkExerciseAsSolvedAsync_UnknownError {
            get {
                return ResourceManager.GetString("MarkExerciseAsSolvedAsync:UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This exercise does not exist..
        /// </summary>
        internal static string ResetExerciseStatusAsync_NotFound {
            get {
                return ResourceManager.GetString("ResetExerciseStatusAsync:NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exercise was reset successfully..
        /// </summary>
        internal static string ResetExerciseStatusAsync_Success {
            get {
                return ResourceManager.GetString("ResetExerciseStatusAsync:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Check the server log for more details..
        /// </summary>
        internal static string ResetExerciseStatusAsync_UnknownError {
            get {
                return ResourceManager.GetString("ResetExerciseStatusAsync:UnknownError", resourceCulture);
            }
        }
    }
}
