//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctf4e.LabServer.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Group_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Group_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ctf4e.LabServer.Resources.Views.Group.de", typeof(Group_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopieren.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        internal static string Docker_Password {
            get {
                return ResourceManager.GetString("Docker:Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zugangsdaten.
        /// </summary>
        internal static string Docker_Title {
            get {
                return ResourceManager.GetString("Docker:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername.
        /// </summary>
        internal static string Docker_Username {
            get {
                return ResourceManager.GetString("Docker:Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestehen.
        /// </summary>
        internal static string Exercises_Admin_Pass {
            get {
                return ResourceManager.GetString("Exercises:Admin:Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Admin) Als gelöst markieren.
        /// </summary>
        internal static string Exercises_Admin_Pass_Text {
            get {
                return ResourceManager.GetString("Exercises:Admin:Pass:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurücksetzen.
        /// </summary>
        internal static string Exercises_Admin_Reset {
            get {
                return ResourceManager.GetString("Exercises:Admin:Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Admin) Zurücksetzen.
        /// </summary>
        internal static string Exercises_Admin_Reset_Text {
            get {
                return ResourceManager.GetString("Exercises:Admin:Reset:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösung eingeben.
        /// </summary>
        internal static string Exercises_Form_Input_Placeholder {
            get {
                return ResourceManager.GetString("Exercises:Form:Input:Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überprüfen.
        /// </summary>
        internal static string Exercises_Form_Submit {
            get {
                return ResourceManager.GetString("Exercises:Form:Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufgabe ausstehend.
        /// </summary>
        internal static string Exercises_Pending {
            get {
                return ResourceManager.GetString("Exercises:Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufgabe gelöst.
        /// </summary>
        internal static string Exercises_Solved {
            get {
                return ResourceManager.GetString("Exercises:Solved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufgabe von Gruppenmitglied gelöst (muss noch selbst gelöst werden).
        /// </summary>
        internal static string Exercises_SolvedByGroupMemberAndNotPassed {
            get {
                return ResourceManager.GetString("Exercises:SolvedByGroupMemberAndNotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufgabe von Gruppenmitglied gelöst (genügt zum Bestehen).
        /// </summary>
        internal static string Exercises_SolvedByGroupMemberAndPassed {
            get {
                return ResourceManager.GetString("Exercises:SolvedByGroupMemberAndPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Aufgabentitel ist ein Link.
        /// </summary>
        internal static string Exercises_TitleIsLink {
            get {
                return ResourceManager.GetString("Exercises:TitleIsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösungen einreichen.
        /// </summary>
        internal static string HtmlTitle {
            get {
                return ResourceManager.GetString("HtmlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachricht.
        /// </summary>
        internal static string Log_Entries_Message {
            get {
                return ResourceManager.GetString("Log:Entries:Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeitstempel.
        /// </summary>
        internal static string Log_Entries_Timestamp {
            get {
                return ResourceManager.GetString("Log:Entries:Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Log ist auf &lt;strong&gt;{0}&lt;/strong&gt; Einträge beschränkt..
        /// </summary>
        internal static string Log_InfoText {
            get {
                return ResourceManager.GetString("Log:InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Log_Title {
            get {
                return ResourceManager.GetString("Log:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Soll die Aufgabe &lt;span class=&quot;font-weight-bold&quot; data-replace=&quot;exercise-name&quot;&gt;&lt;/span&gt; wirklich als gelöst markiert werden?&lt;/p&gt;&lt;p&gt;Hinweis: Dies löst ebenfalls eine Benachrichtigung an das CTF-System aus.&lt;/p&gt;.
        /// </summary>
        internal static string Modal_MarkExerciseSolved_Body {
            get {
                return ResourceManager.GetString("Modal:MarkExerciseSolved:Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als gelöst markieren.
        /// </summary>
        internal static string Modal_MarkExerciseSolved_Submit {
            get {
                return ResourceManager.GetString("Modal:MarkExerciseSolved:Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufgabe als gelöst markieren.
        /// </summary>
        internal static string Modal_MarkExerciseSolved_Title {
            get {
                return ResourceManager.GetString("Modal:MarkExerciseSolved:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Soll die Aufgabe &lt;span class=&quot;font-weight-bold&quot; data-replace=&quot;exercise-name&quot;&gt;&lt;/span&gt; wirklich zurückgesetzt werden?&lt;/p&gt;&lt;p&gt;Hinweis: Dies setzt lediglich den Status der Aufgabe auf diesem Server zurück; existierende Einreichungen im CTF-System bleiben unberührt und müssen manuell gelöscht werden.&lt;/p&gt;.
        /// </summary>
        internal static string Modal_ResetExercise_Body {
            get {
                return ResourceManager.GetString("Modal:ResetExercise:Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurücksetzen.
        /// </summary>
        internal static string Modal_ResetExercise_Submit {
            get {
                return ResourceManager.GetString("Modal:ResetExercise:Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufgabe zurücksetzen.
        /// </summary>
        internal static string Modal_ResetExercise_Title {
            get {
                return ResourceManager.GetString("Modal:ResetExercise:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösungen einreichen.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
