//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctf4e.LabServer.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Group {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Group() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ctf4e.LabServer.Resources.Views.Group", typeof(Group).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        internal static string Credentials {
            get {
                return ResourceManager.GetString("Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Docker_Password {
            get {
                return ResourceManager.GetString("Docker:Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        internal static string Docker_Title {
            get {
                return ResourceManager.GetString("Docker:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string Docker_Username {
            get {
                return ResourceManager.GetString("Docker:Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        internal static string Exercises_Admin_Pass {
            get {
                return ResourceManager.GetString("Exercises:Admin:Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Admin) Mark as solved.
        /// </summary>
        internal static string Exercises_Admin_Pass_Text {
            get {
                return ResourceManager.GetString("Exercises:Admin:Pass:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Exercises_Admin_Reset {
            get {
                return ResourceManager.GetString("Exercises:Admin:Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Admin) Reset.
        /// </summary>
        internal static string Exercises_Admin_Reset_Text {
            get {
                return ResourceManager.GetString("Exercises:Admin:Reset:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert solution.
        /// </summary>
        internal static string Exercises_Form_Input_Placeholder {
            get {
                return ResourceManager.GetString("Exercises:Form:Input:Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string Exercises_Form_Submit {
            get {
                return ResourceManager.GetString("Exercises:Form:Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise pending.
        /// </summary>
        internal static string Exercises_Pending {
            get {
                return ResourceManager.GetString("Exercises:Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise solved.
        /// </summary>
        internal static string Exercises_Solved {
            get {
                return ResourceManager.GetString("Exercises:Solved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise solved by group member (still needs to be solved by you).
        /// </summary>
        internal static string Exercises_SolvedByGroupMemberAndNotPassed {
            get {
                return ResourceManager.GetString("Exercises:SolvedByGroupMemberAndNotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise solved by group member (sufficient for passing the lab).
        /// </summary>
        internal static string Exercises_SolvedByGroupMemberAndPassed {
            get {
                return ResourceManager.GetString("Exercises:SolvedByGroupMemberAndPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exercise title is a link.
        /// </summary>
        internal static string Exercises_TitleIsLink {
            get {
                return ResourceManager.GetString("Exercises:TitleIsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit solutions.
        /// </summary>
        internal static string HtmlTitle {
            get {
                return ResourceManager.GetString("HtmlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Log_Entries_Message {
            get {
                return ResourceManager.GetString("Log:Entries:Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string Log_Entries_Timestamp {
            get {
                return ResourceManager.GetString("Log:Entries:Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log is limited to &lt;strong&gt;{0}&lt;/strong&gt; entries..
        /// </summary>
        internal static string Log_InfoText {
            get {
                return ResourceManager.GetString("Log:InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Log_Title {
            get {
                return ResourceManager.GetString("Log:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Do you really want to mark the exercise &lt;span class=&quot;font-weight-bold&quot; data-replace=&quot;exercise-name&quot;&gt;&lt;/span&gt; as solved?&lt;/p&gt;&lt;p&gt;Note: This will trigger a message to the CTF system.&lt;/p&gt;.
        /// </summary>
        internal static string Modal_MarkExerciseSolved_Body {
            get {
                return ResourceManager.GetString("Modal:MarkExerciseSolved:Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as solved.
        /// </summary>
        internal static string Modal_MarkExerciseSolved_Submit {
            get {
                return ResourceManager.GetString("Modal:MarkExerciseSolved:Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark exercise as solved.
        /// </summary>
        internal static string Modal_MarkExerciseSolved_Title {
            get {
                return ResourceManager.GetString("Modal:MarkExerciseSolved:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Do you really want to reset the exercise &lt;span class=&quot;font-weight-bold&quot; data-replace=&quot;exercise-name&quot;&gt;&lt;/span&gt;?&lt;/p&gt;&lt;p&gt;Note: This only resets the exercise state on this server; existing submissions in the CTF system will remain untouched and need to be deleted manually.&lt;/p&gt;.
        /// </summary>
        internal static string Modal_ResetExercise_Body {
            get {
                return ResourceManager.GetString("Modal:ResetExercise:Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Modal_ResetExercise_Submit {
            get {
                return ResourceManager.GetString("Modal:ResetExercise:Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset exercise.
        /// </summary>
        internal static string Modal_ResetExercise_Title {
            get {
                return ResourceManager.GetString("Modal:ResetExercise:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit solutions.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
