services:
  ctf4e-server:
    image: ctf4e/ctf4e-server:latest
    volumes:
      - type: bind
        source: ./appsettings.Production.json
        target: /app/appsettings.Production.json
        read_only: true
    environment:
      # Enable these for HTTPS support
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/config/${CERT_FILE_NAME}
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
    ports:
      - "80:80"
    depends_on:
      - ctf4e-database
  
  ctf4e-database:
    image: library/mariadb:lts
    volumes:
      - type: volume
        source: ctf4e-state
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}

volumes:
  ctf4e-state:
