//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctf4e.Server.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdminLabExecutions_CreateForSlot_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminLabExecutions_CreateForSlot_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ctf4e.Server.Resources.Views.AdminLabExecutions.CreateForSlot.de", typeof(AdminLabExecutions_CreateForSlot_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string Form_Cancel {
            get {
                return ResourceManager.GetString("Form:Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktikum.
        /// </summary>
        internal static string Form_LabId {
            get {
                return ResourceManager.GetString("Form:LabId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktikum auswählen.
        /// </summary>
        internal static string Form_LabId_Placeholder {
            get {
                return ResourceManager.GetString("Form:LabId:Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für alle Gruppen erzwingen.
        /// </summary>
        internal static string Form_OverrideExisting {
            get {
                return ResourceManager.GetString("Form:OverrideExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dies überschreibt sämtliche manuellen Anpassungen, die eventuell bei einigen Gruppen in diesem Slot vorgenommen worden sind..
        /// </summary>
        internal static string Form_OverrideExisting_Description {
            get {
                return ResourceManager.GetString("Form:OverrideExisting:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminslot.
        /// </summary>
        internal static string Form_SlotId {
            get {
                return ResourceManager.GetString("Form:SlotId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminslot auswählen.
        /// </summary>
        internal static string Form_SlotId_Placeholder {
            get {
                return ResourceManager.GetString("Form:SlotId:Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktikum starten.
        /// </summary>
        internal static string Form_Submit {
            get {
                return ResourceManager.GetString("Form:Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktikum für alle Gruppen eines Termins starten.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
