//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctf4e.Server.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdminScoreboard_Statistics_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminScoreboard_Statistics_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ctf4e.Server.Resources.Views.AdminScoreboard.Statistics.de", typeof(AdminScoreboard_Statistics_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug-Bounty.
        /// </summary>
        internal static string BugBounty {
            get {
                return ResourceManager.GetString("BugBounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Exercises_Name {
            get {
                return ResourceManager.GetString("Exercises:Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr..
        /// </summary>
        internal static string Exercises_Number {
            get {
                return ResourceManager.GetString("Exercises:Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestandene Einreichungen.
        /// </summary>
        internal static string Exercises_Passed {
            get {
                return ResourceManager.GetString("Exercises:Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkte.
        /// </summary>
        internal static string Exercises_Points {
            get {
                return ResourceManager.GetString("Exercises:Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufgaben.
        /// </summary>
        internal static string ExercisesTitle {
            get {
                return ResourceManager.GetString("ExercisesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        internal static string Flags_Description {
            get {
                return ResourceManager.GetString("Flags:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkte.
        /// </summary>
        internal static string Flags_Points {
            get {
                return ResourceManager.GetString("Flags:Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einreichungen.
        /// </summary>
        internal static string Flags_Submissions {
            get {
                return ResourceManager.GetString("Flags:Submissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags (alle Terminslots).
        /// </summary>
        internal static string FlagsTitle {
            get {
                return ResourceManager.GetString("FlagsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pflicht.
        /// </summary>
        internal static string Mandatory {
            get {
                return ResourceManager.GetString("Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistiken.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
