//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctf4e.Server.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdminUsers_Edit_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminUsers_Edit_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ctf4e.Server.Resources.Views.AdminUsers.Edit.de", typeof(AdminUsers_Edit_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string Form_Cancel {
            get {
                return ResourceManager.GetString("Form:Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Form_DisplayName {
            get {
                return ResourceManager.GetString("Form:DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppencode.
        /// </summary>
        internal static string Form_GroupFindingCode {
            get {
                return ResourceManager.GetString("Form:GroupFindingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppe.
        /// </summary>
        internal static string Form_GroupId {
            get {
                return ResourceManager.GetString("Form:GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (keine).
        /// </summary>
        internal static string Form_GroupId_None {
            get {
                return ResourceManager.GetString("Form:GroupId:None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutor (nicht im Scoreboard sichtbar).
        /// </summary>
        internal static string Form_IsTutor {
            get {
                return ResourceManager.GetString("Form:IsTutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moodle-Account.
        /// </summary>
        internal static string Form_MoodleName {
            get {
                return ResourceManager.GetString("Form:MoodleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen speichern.
        /// </summary>
        internal static string Form_Submit {
            get {
                return ResourceManager.GetString("Form:Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allgemeine Einstellungen.
        /// </summary>
        internal static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminrechte.
        /// </summary>
        internal static string Privilege_Admin {
            get {
                return ResourceManager.GetString("Privilege:Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einträge im Admin-Scoreboard bearbeiten: Aufgaben/Flag-Einreichungen erstellen/bearbeiten/löschen.
        /// </summary>
        internal static string Privilege_EditAdminScoreboard {
            get {
                return ResourceManager.GetString("Privilege:EditAdminScoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguration bearbeiten.
        /// </summary>
        internal static string Privilege_EditConfiguration {
            get {
                return ResourceManager.GetString("Privilege:EditConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppen bearbeiten.
        /// </summary>
        internal static string Privilege_EditGroups {
            get {
                return ResourceManager.GetString("Privilege:EditGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktive Praktika bearbeiten.
        /// </summary>
        internal static string Privilege_EditLabExecutions {
            get {
                return ResourceManager.GetString("Privilege:EditLabExecutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktika/Aufgaben/Flags bearbeiten.
        /// </summary>
        internal static string Privilege_EditLabs {
            get {
                return ResourceManager.GetString("Privilege:EditLabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminslots bearbeiten.
        /// </summary>
        internal static string Privilege_EditSlots {
            get {
                return ResourceManager.GetString("Privilege:EditSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer bearbeiten.
        /// </summary>
        internal static string Privilege_EditUsers {
            get {
                return ResourceManager.GetString("Privilege:EditUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin-Zugriff auf Praktikumsserver (via Admin-Scoreboard).
        /// </summary>
        internal static string Privilege_LoginAsLabServerAdmin {
            get {
                return ResourceManager.GetString("Privilege:LoginAsLabServerAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergebnisse synchronisieren/importieren/exportieren.
        /// </summary>
        internal static string Privilege_TransferResults {
            get {
                return ResourceManager.GetString("Privilege:TransferResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin-Scoreboard einsehen.
        /// </summary>
        internal static string Privilege_ViewAdminScoreboard {
            get {
                return ResourceManager.GetString("Privilege:ViewAdminScoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppen einsehen.
        /// </summary>
        internal static string Privilege_ViewGroups {
            get {
                return ResourceManager.GetString("Privilege:ViewGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktive Praktika einsehen.
        /// </summary>
        internal static string Privilege_ViewLabExecutions {
            get {
                return ResourceManager.GetString("Privilege:ViewLabExecutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktika/Aufgaben/Flags einsehen.
        /// </summary>
        internal static string Privilege_ViewLabs {
            get {
                return ResourceManager.GetString("Privilege:ViewLabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminslots einsehen.
        /// </summary>
        internal static string Privilege_ViewSlots {
            get {
                return ResourceManager.GetString("Privilege:ViewSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer einsehen.
        /// </summary>
        internal static string Privilege_ViewUsers {
            get {
                return ResourceManager.GetString("Privilege:ViewUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zugriffsrechte.
        /// </summary>
        internal static string Privileges {
            get {
                return ResourceManager.GetString("Privileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer bearbeiten.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
