//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctf4e.Server.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdminUsers_List_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminUsers_List_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ctf4e.Server.Resources.Views.AdminUsers.List.de", typeof(AdminUsers_List_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktionen.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer verwalten.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppe bearbeiten.
        /// </summary>
        internal static string Users_EditGroup_Text {
            get {
                return ResourceManager.GetString("Users:EditGroup:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppencode.
        /// </summary>
        internal static string Users_GroupCode {
            get {
                return ResourceManager.GetString("Users:GroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppe.
        /// </summary>
        internal static string Users_GroupId {
            get {
                return ResourceManager.GetString("Users:GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Users_Id {
            get {
                return ResourceManager.GetString("Users:Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutor.
        /// </summary>
        internal static string Users_IsTutor {
            get {
                return ResourceManager.GetString("Users:IsTutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ist Tutor und wird daher nicht im Scoreboard angezeigt.
        /// </summary>
        internal static string Users_IsTutor_Text {
            get {
                return ResourceManager.GetString("Users:IsTutor:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moodle-Account.
        /// </summary>
        internal static string Users_MoodleAccount {
            get {
                return ResourceManager.GetString("Users:MoodleAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Users_Name {
            get {
                return ResourceManager.GetString("Users:Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zugriffsrechte.
        /// </summary>
        internal static string Users_Privileges {
            get {
                return ResourceManager.GetString("Users:Privileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminrechte.
        /// </summary>
        internal static string Users_Privileges_Admin {
            get {
                return ResourceManager.GetString("Users:Privileges:Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin-Scoreboard bearbeiten.
        /// </summary>
        internal static string Users_Privileges_EditAdminScoreboard {
            get {
                return ResourceManager.GetString("Users:Privileges:EditAdminScoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguration bearbeiten.
        /// </summary>
        internal static string Users_Privileges_EditConfiguration {
            get {
                return ResourceManager.GetString("Users:Privileges:EditConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppen bearbeiten.
        /// </summary>
        internal static string Users_Privileges_EditGroups {
            get {
                return ResourceManager.GetString("Users:Privileges:EditGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktive Praktika bearbeiten.
        /// </summary>
        internal static string Users_Privileges_EditLabExecutions {
            get {
                return ResourceManager.GetString("Users:Privileges:EditLabExecutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktika/Aufgaben/Flags bearbeiten.
        /// </summary>
        internal static string Users_Privileges_EditLabs {
            get {
                return ResourceManager.GetString("Users:Privileges:EditLabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminslots bearbeiten.
        /// </summary>
        internal static string Users_Privileges_EditSlots {
            get {
                return ResourceManager.GetString("Users:Privileges:EditSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer bearbeiten.
        /// </summary>
        internal static string Users_Privileges_EditUsers {
            get {
                return ResourceManager.GetString("Users:Privileges:EditUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin-Zugriff auf Praktikumsserver (via Admin-Scoreboard).
        /// </summary>
        internal static string Users_Privileges_LoginAsLabServerAdmin {
            get {
                return ResourceManager.GetString("Users:Privileges:LoginAsLabServerAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergebnisse synchronisieren/importieren/exportieren.
        /// </summary>
        internal static string Users_Privileges_TransferResults {
            get {
                return ResourceManager.GetString("Users:Privileges:TransferResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin-Scoreboard einsehen.
        /// </summary>
        internal static string Users_Privileges_ViewAdminScoreboard {
            get {
                return ResourceManager.GetString("Users:Privileges:ViewAdminScoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppen einsehen.
        /// </summary>
        internal static string Users_Privileges_ViewGroups {
            get {
                return ResourceManager.GetString("Users:Privileges:ViewGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktive Praktika einsehen.
        /// </summary>
        internal static string Users_Privileges_ViewLabExecutions {
            get {
                return ResourceManager.GetString("Users:Privileges:ViewLabExecutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktika/Aufgaben/Flags einsehen.
        /// </summary>
        internal static string Users_Privileges_ViewLabs {
            get {
                return ResourceManager.GetString("Users:Privileges:ViewLabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminslots einsehen.
        /// </summary>
        internal static string Users_Privileges_ViewSlots {
            get {
                return ResourceManager.GetString("Users:Privileges:ViewSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer einsehen.
        /// </summary>
        internal static string Users_Privileges_ViewUsers {
            get {
                return ResourceManager.GetString("Users:Privileges:ViewUsers", resourceCulture);
            }
        }
    }
}
