//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctf4e.Server.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdminLabs_List_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminLabs_List_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ctf4e.Server.Resources.Views.AdminLabs.List.de", typeof(AdminLabs_List_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktionen.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktikum erstellen.
        /// </summary>
        internal static string CreateLab {
            get {
                return ResourceManager.GetString("CreateLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufgaben.
        /// </summary>
        internal static string Labs_Exercises {
            get {
                return ResourceManager.GetString("Labs:Exercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufgabenliste öffnen.
        /// </summary>
        internal static string Labs_Exercises_Text {
            get {
                return ResourceManager.GetString("Labs:Exercises:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        internal static string Labs_Flags {
            get {
                return ResourceManager.GetString("Labs:Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flagliste öffnen.
        /// </summary>
        internal static string Labs_Flags_Text {
            get {
                return ResourceManager.GetString("Labs:Flags:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Labs_ID {
            get {
                return ResourceManager.GetString("Labs:ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Flag-Punkte.
        /// </summary>
        internal static string Labs_MaximumFlagPoints {
            get {
                return ResourceManager.GetString("Labs:MaximumFlagPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Punkte.
        /// </summary>
        internal static string Labs_MaximumPoints {
            get {
                return ResourceManager.GetString("Labs:MaximumPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Labs_Name {
            get {
                return ResourceManager.GetString("Labs:Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sichtbar?.
        /// </summary>
        internal static string Labs_Visible {
            get {
                return ResourceManager.GetString("Labs:Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Wollen Sie das Praktikum &amp;quot;&lt;span data-replace=&quot;lab-name&quot;&gt;&lt;/span&gt;&amp;quot; wirklich löschen?&lt;/p&gt;&lt;p&gt;Beachten Sie, dass hierbei auch alle damit zusammenhängenden Aufgaben und Flags unwiderruflich gelöscht werden!&lt;/p&gt;.
        /// </summary>
        internal static string Modal_DeleteLab_Body {
            get {
                return ResourceManager.GetString("Modal:DeleteLab:Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktikum löschen.
        /// </summary>
        internal static string Modal_DeleteLab_Submit {
            get {
                return ResourceManager.GetString("Modal:DeleteLab:Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktikum löschen.
        /// </summary>
        internal static string Modal_DeleteLab_Title {
            get {
                return ResourceManager.GetString("Modal:DeleteLab:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktika verwalten.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
