//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctf4e.Server.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdminConfiguration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminConfiguration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ctf4e.Server.Resources.Views.AdminConfiguration", typeof(AdminConfiguration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of flag submission until point median.
        /// </summary>
        internal static string Config_FlagHalfPointsSubmissionCount {
            get {
                return ResourceManager.GetString("Config:FlagHalfPointsSubmissionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This controls the number of flag submissions where the median between base points and minimum points (&lt;code&gt;(base+min)/2&lt;/code&gt;) is granted..
        /// </summary>
        internal static string Config_FlagHalfPointsSubmissionCount_Description {
            get {
                return ResourceManager.GetString("Config:FlagHalfPointsSubmissionCount:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisor for maximum flag points.
        /// </summary>
        internal static string Config_FlagMinimumPointsDivisor {
            get {
                return ResourceManager.GetString("Config:FlagMinimumPointsDivisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum points for any flag are computed by dividing its base points through this number..
        /// </summary>
        internal static string Config_FlagMinimumPointsDivisor_Description {
            get {
                return ResourceManager.GetString("Config:FlagMinimumPointsDivisor:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text on group selection page.
        /// </summary>
        internal static string Config_GroupSelectionPageText {
            get {
                return ResourceManager.GetString("Config:GroupSelectionPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This text is shown on top of the group selection page. It should contain information regarding how groups are formed and how they can register in the CTF system. This field supports Markdown styling..
        /// </summary>
        internal static string Config_GroupSelectionPageText_Description {
            get {
                return ResourceManager.GetString("Config:GroupSelectionPageText:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show group selection page.
        /// </summary>
        internal static string Config_GroupSelectionPageText_ShowPage {
            get {
                return ResourceManager.GetString("Config:GroupSelectionPageText:ShowPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum group size.
        /// </summary>
        internal static string Config_GroupSizeMax {
            get {
                return ResourceManager.GetString("Config:GroupSizeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This number controls the maximum amount of members in a group. Only admins can create larger groups..
        /// </summary>
        internal static string Config_GroupSizeMax_Description {
            get {
                return ResourceManager.GetString("Config:GroupSizeMax:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum group size.
        /// </summary>
        internal static string Config_GroupSizeMin {
            get {
                return ResourceManager.GetString("Config:GroupSizeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This number controls the minimum amount of members in a group. Thus, each participant must find enough other participants in order to form a group of the given size. Only admins can create larger groups..
        /// </summary>
        internal static string Config_GroupSizeMin_Description {
            get {
                return ResourceManager.GetString("Config:GroupSizeMin:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation title.
        /// </summary>
        internal static string Config_NavbarTitle {
            get {
                return ResourceManager.GetString("Config:NavbarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This title is shown on the top left in the navigation..
        /// </summary>
        internal static string Config_NavbarTitle_Description {
            get {
                return ResourceManager.GetString("Config:NavbarTitle:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page title.
        /// </summary>
        internal static string Config_PageTitle {
            get {
                return ResourceManager.GetString("Config:PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This title is shown in the HTML &lt;code&gt;&amp;lt;title&amp;gt;&lt;/code&gt; element..
        /// </summary>
        internal static string Config_PageTitle_Description {
            get {
                return ResourceManager.GetString("Config:PageTitle:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass as group.
        /// </summary>
        internal static string Config_PassAsGroup {
            get {
                return ResourceManager.GetString("Config:PassAsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this is active, all submissions are evaluated at group level. Thus, it does not matter which group member has submitted an exercise. This setting does not influence the scoreboard..
        /// </summary>
        internal static string Config_PassAsGroup_Description {
            get {
                return ResourceManager.GetString("Config:PassAsGroup:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoreboard cache duration in seconds.
        /// </summary>
        internal static string Config_ScoreboardCachedSeconds {
            get {
                return ResourceManager.GetString("Config:ScoreboardCachedSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This number controls the amount of time where a cached scoreboard is valid, before a new one is generated. The cache is designed to reduce database load, as the necessary queries are quite expensive. This value should be set as low as possible, and should only be increased if necessary..
        /// </summary>
        internal static string Config_ScoreboardCachedSeconds_Description {
            get {
                return ResourceManager.GetString("Config:ScoreboardCachedSeconds:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of entries in public scoreboard.
        /// </summary>
        internal static string Config_ScoreboardEntryCount {
            get {
                return ResourceManager.GetString("Config:ScoreboardEntryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This controls the number of entries in the public scoreboard, which all participants can see (admins can view all entries). The scoreboard may show more entries in case multiple groups share a given rank..
        /// </summary>
        internal static string Config_ScoreboardEntryCount_Description {
            get {
                return ResourceManager.GetString("Config:ScoreboardEntryCount:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Status_BuildVersion {
            get {
                return ResourceManager.GetString("Status:BuildVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current culture.
        /// </summary>
        internal static string Status_CurrentCulture {
            get {
                return ResourceManager.GetString("Status:CurrentCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current time.
        /// </summary>
        internal static string Status_Now {
            get {
                return ResourceManager.GetString("Status:Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current time (UTC).
        /// </summary>
        internal static string Status_NowUtc {
            get {
                return ResourceManager.GetString("Status:NowUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time zone.
        /// </summary>
        internal static string Status_Timezone {
            get {
                return ResourceManager.GetString("Status:Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status_Title {
            get {
                return ResourceManager.GetString("Status:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit configuration.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag base points.
        /// </summary>
        internal static string Visualization_BasePoints {
            get {
                return ResourceManager.GetString("Visualization:BasePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph shows the trend of the flag points depending on the number of submissions..
        /// </summary>
        internal static string Visualization_Description {
            get {
                return ResourceManager.GetString("Visualization:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag points.
        /// </summary>
        internal static string Visualization_FlagPoints {
            get {
                return ResourceManager.GetString("Visualization:FlagPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group count.
        /// </summary>
        internal static string Visualization_GroupCount {
            get {
                return ResourceManager.GetString("Visualization:GroupCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization of flag points.
        /// </summary>
        internal static string Visualization_Title {
            get {
                return ResourceManager.GetString("Visualization:Title", resourceCulture);
            }
        }
    }
}
