//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctf4e.Server.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdminFlags_Create_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminFlags_Create_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ctf4e.Server.Resources.Views.AdminFlags.Create.de", typeof(AdminFlags_Create_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basispunktzahl.
        /// </summary>
        internal static string Form_BasePoints {
            get {
                return ResourceManager.GetString("Form:BasePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string Form_Cancel {
            get {
                return ResourceManager.GetString("Form:Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag-Code.
        /// </summary>
        internal static string Form_Code {
            get {
                return ResourceManager.GetString("Form:Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        internal static string Form_Description {
            get {
                return ResourceManager.GetString("Form:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug-Bounty?.
        /// </summary>
        internal static string Form_IsBounty {
            get {
                return ResourceManager.GetString("Form:IsBounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug-Bounty-Flags werden nicht skaliert, sondern ergeben unabhängig von der Anzahl der Einlösungen immer dieselbe Punktzahl..
        /// </summary>
        internal static string Form_IsBounty_Description {
            get {
                return ResourceManager.GetString("Form:IsBounty:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag erstellen.
        /// </summary>
        internal static string Form_Submit {
            get {
                return ResourceManager.GetString("Form:Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag erstellen und fortfahren.
        /// </summary>
        internal static string Form_SubmitAndContinue {
            get {
                return ResourceManager.GetString("Form:SubmitAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag erstellen.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
