//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctf4e.Server.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Authentication_GroupSelection_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Authentication_GroupSelection_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ctf4e.Server.Resources.Views.Authentication.GroupSelection.de", typeof(Authentication_GroupSelection_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Ihrer Gruppe.
        /// </summary>
        internal static string Form_DisplayName {
            get {
                return ResourceManager.GetString("Form:DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Feld hat volle Unicode-Unterstützung, Ihrer Kreativität sind abgesehen von der Längenbeschränkung also keine Grenzen gesetzt. Der Gruppenname kann anschließend nicht mehr geändert werden..
        /// </summary>
        internal static string Form_DisplayName_Description {
            get {
                return ResourceManager.GetString("Form:DisplayName:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alles ausgefüllt? Super! Bitte überprüfen Sie sicherheitshalber nochmal alle Angaben. Nach erfolgreichem Erstellen der Gruppe werden Sie automatisch ausgeloggt und müssen sich einmal erneut einloggen. Im Anschluss haben Sie Zugriff auf den Arbeitsbereich Ihrer Gruppe..
        /// </summary>
        internal static string Form_FinalText {
            get {
                return ResourceManager.GetString("Form:FinalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codes Ihrer Gruppenpartner/Gruppenpartnerinnen.
        /// </summary>
        internal static string Form_OtherUserCodes {
            get {
                return ResourceManager.GetString("Form:OtherUserCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Code pro Zeile..
        /// </summary>
        internal static string Form_OtherUserCodes_Description {
            get {
                return ResourceManager.GetString("Form:OtherUserCodes:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am CTF teilnehmen und Gruppe im Scoreboard anzeigen.
        /// </summary>
        internal static string Form_ShowInScoreboard {
            get {
                return ResourceManager.GetString("Form:ShowInScoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit Setzen dieses Feldes nehmen Sie am Praktikums-internen Capture-The-Flag teil, und Ihr Gruppenname wird im Scoreboard angezeigt. Die Teilnahme am CTF ist komplett freiwillig und hat keinerlei Nachteile. Das Scoreboard zeigt stets nur die oberen Plätze an..
        /// </summary>
        internal static string Form_ShowInScoreboard_Description {
            get {
                return ResourceManager.GetString("Form:ShowInScoreboard:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktikumstermin.
        /// </summary>
        internal static string Form_SlotId {
            get {
                return ResourceManager.GetString("Form:SlotId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert dieses Felds muss mit dem Ihnen während der Terminwahl zugewiesenen Termin übereinstimmen..
        /// </summary>
        internal static string Form_SlotId_Description {
            get {
                return ResourceManager.GetString("Form:SlotId:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppe erstellen.
        /// </summary>
        internal static string Form_Submit {
            get {
                return ResourceManager.GetString("Form:Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppe gründen.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Code lautet: &lt;span class=&quot;fw-bold font-monospace&quot;&gt;{0}&lt;/span&gt;.
        /// </summary>
        internal static string YourCode {
            get {
                return ResourceManager.GetString("YourCode", resourceCulture);
            }
        }
    }
}
