//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctf4e.Server.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Authentication_Login {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Authentication_Login() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ctf4e.Server.Resources.Views.Authentication.Login", typeof(Authentication_Login).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string DevLogin_Submit {
            get {
                return ResourceManager.GetString("DevLogin:Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer login.
        /// </summary>
        internal static string DevLogin_Title {
            get {
                return ResourceManager.GetString("DevLogin:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user.
        /// </summary>
        internal static string DevLogin_UserId {
            get {
                return ResourceManager.GetString("DevLogin:UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Moodle course.
        /// </summary>
        internal static string MoodleLogin_Button {
            get {
                return ResourceManager.GetString("MoodleLogin:Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login via Moodle.
        /// </summary>
        internal static string MoodleLogin_Title {
            get {
                return ResourceManager.GetString("MoodleLogin:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordLogin_Password {
            get {
                return ResourceManager.GetString("PasswordLogin:Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string PasswordLogin_Submit {
            get {
                return ResourceManager.GetString("PasswordLogin:Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login via Password.
        /// </summary>
        internal static string PasswordLogin_Title {
            get {
                return ResourceManager.GetString("PasswordLogin:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string PasswordLogin_Username {
            get {
                return ResourceManager.GetString("PasswordLogin:Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        internal static string Tab_DevLogin {
            get {
                return ResourceManager.GetString("Tab:DevLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moodle.
        /// </summary>
        internal static string Tab_MoodleLogin {
            get {
                return ResourceManager.GetString("Tab:MoodleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Tab_PasswordLogin {
            get {
                return ResourceManager.GetString("Tab:PasswordLogin", resourceCulture);
            }
        }
    }
}
