//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctf4e.Server.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scoreboard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scoreboard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ctf4e.Server.Resources.Views.Scoreboard", typeof(Scoreboard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For admins only.
        /// </summary>
        internal static string AdminsOnly {
            get {
                return ResourceManager.GetString("AdminsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All labs.
        /// </summary>
        internal static string AllLabs {
            get {
                return ResourceManager.GetString("AllLabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (all).
        /// </summary>
        internal static string AllSlots {
            get {
                return ResourceManager.GetString("AllSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically reload after (seconds).
        /// </summary>
        internal static string AutoReload {
            get {
                return ResourceManager.GetString("AutoReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalidate cache and reload from database.
        /// </summary>
        internal static string ResetCache {
            get {
                return ResourceManager.GetString("ResetCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Exercises: {0}, Flags: {1}).
        /// </summary>
        internal static string Scoreboard_DetailedPoints {
            get {
                return ResourceManager.GetString("Scoreboard:DetailedPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Exercises: {0}, Flags: {1}, Bugs: {2}).
        /// </summary>
        internal static string Scoreboard_DetailedPointsWithBugs {
            get {
                return ResourceManager.GetString("Scoreboard:DetailedPointsWithBugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        internal static string Scoreboard_Flags {
            get {
                return ResourceManager.GetString("Scoreboard:Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This group got a bug bounty..
        /// </summary>
        internal static string Scoreboard_GotBugBounty {
            get {
                return ResourceManager.GetString("Scoreboard:GotBugBounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Scoreboard_Group {
            get {
                return ResourceManager.GetString("Scoreboard:Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last submission: {0}.
        /// </summary>
        internal static string Scoreboard_LastSubmission {
            get {
                return ResourceManager.GetString("Scoreboard:LastSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string Scoreboard_Points {
            get {
                return ResourceManager.GetString("Scoreboard:Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select scoreboard.
        /// </summary>
        internal static string SelectScoreboard {
            get {
                return ResourceManager.GetString("SelectScoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (hidden).
        /// </summary>
        internal static string SelectScoreboard_HiddenLab {
            get {
                return ResourceManager.GetString("SelectScoreboard:HiddenLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select time slot.
        /// </summary>
        internal static string SelectSlot {
            get {
                return ResourceManager.GetString("SelectSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all entries.
        /// </summary>
        internal static string ShowAllEntries {
            get {
                return ResourceManager.GetString("ShowAllEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show selected scoreboard.
        /// </summary>
        internal static string ShowSelectedScoreboard {
            get {
                return ResourceManager.GetString("ShowSelectedScoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All time slots.
        /// </summary>
        internal static string Title_AllSlots {
            get {
                return ResourceManager.GetString("Title:AllSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoreboard: All Labs.
        /// </summary>
        internal static string Title_ScoreboardAll {
            get {
                return ResourceManager.GetString("Title:ScoreboardAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab Scoreboard: {0}.
        /// </summary>
        internal static string Title_ScoreboardLab {
            get {
                return ResourceManager.GetString("Title:ScoreboardLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time slot: {0}.
        /// </summary>
        internal static string Title_Slot {
            get {
                return ResourceManager.GetString("Title:Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For tutors and admins only.
        /// </summary>
        internal static string TutorsAndAdminsOnly {
            get {
                return ResourceManager.GetString("TutorsAndAdminsOnly", resourceCulture);
            }
        }
    }
}
