//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctf4e.Server.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserDashboard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserDashboard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ctf4e.Server.Resources.Views.UserDashboard", typeof(UserDashboard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercises.
        /// </summary>
        internal static string Exercises {
            get {
                return ResourceManager.GetString("Exercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tries: {0} valid, {1} total.
        /// </summary>
        internal static string Exercises_SubmissionStatistic {
            get {
                return ResourceManager.GetString("Exercises:SubmissionStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct solution?.
        /// </summary>
        internal static string ExerciseSubmissions_Correct {
            get {
                return ResourceManager.GetString("ExerciseSubmissions:Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group member.
        /// </summary>
        internal static string ExerciseSubmissions_GroupMember {
            get {
                return ResourceManager.GetString("ExerciseSubmissions:GroupMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This solution attempt was submitted outside of the lab time..
        /// </summary>
        internal static string ExerciseSubmissions_Invalid {
            get {
                return ResourceManager.GetString("ExerciseSubmissions:Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission time.
        /// </summary>
        internal static string ExerciseSubmissions_Timestamp {
            get {
                return ResourceManager.GetString("ExerciseSubmissions:Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        internal static string Flags {
            get {
                return ResourceManager.GetString("Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All found.
        /// </summary>
        internal static string Flags_AllFound {
            get {
                return ResourceManager.GetString("Flags:AllFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag code.
        /// </summary>
        internal static string Flags_FlagCode {
            get {
                return ResourceManager.GetString("Flags:FlagCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found flags.
        /// </summary>
        internal static string Flags_FoundFlags {
            get {
                return ResourceManager.GetString("Flags:FoundFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} valid, {1} total.
        /// </summary>
        internal static string Flags_SubmissionStatistic {
            get {
                return ResourceManager.GetString("Flags:SubmissionStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit flag.
        /// </summary>
        internal static string Flags_SubmitFlag {
            get {
                return ResourceManager.GetString("Flags:SubmitFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string FlagSubmissions_Code {
            get {
                return ResourceManager.GetString("FlagSubmissions:Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group member.
        /// </summary>
        internal static string FlagSubmissions_GroupMember {
            get {
                return ResourceManager.GetString("FlagSubmissions:GroupMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This flag was submitted outside of the lab time..
        /// </summary>
        internal static string FlagSubmissions_Invalid {
            get {
                return ResourceManager.GetString("FlagSubmissions:Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission time.
        /// </summary>
        internal static string FlagSubmissions_Timestamp {
            get {
                return ResourceManager.GetString("FlagSubmissions:Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab.
        /// </summary>
        internal static string Lab {
            get {
                return ResourceManager.GetString("Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This lab has not yet started. You can neither work on exercises nor submit flags.&lt;br&gt;The lab is scheduled to start at &lt;strong&gt;{0:g}&lt;/strong&gt;..
        /// </summary>
        internal static string LabExecutionStatus_BeforePreStart_Text {
            get {
                return ResourceManager.GetString("LabExecutionStatus:BeforePreStart:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for start.
        /// </summary>
        internal static string LabExecutionStatus_BeforePreStart_Title {
            get {
                return ResourceManager.GetString("LabExecutionStatus:BeforePreStart:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This lab has ended. You can still work an exercises and submit flags; however, those won&apos;t be considered for grading and won&apos;t be reflected in the scoreboard..
        /// </summary>
        internal static string LabExecutionStatus_End_Text {
            get {
                return ResourceManager.GetString("LabExecutionStatus:End:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended.
        /// </summary>
        internal static string LabExecutionStatus_End_Title {
            get {
                return ResourceManager.GetString("LabExecutionStatus:End:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This lab is in the preparatory phase. You can work on certain selected exercises and submit all flags.&lt;br&gt;Begin of main working time: &lt;strong&gt;{0:g}&lt;/strong&gt;..
        /// </summary>
        internal static string LabExecutionStatus_PreStart_Text {
            get {
                return ResourceManager.GetString("LabExecutionStatus:PreStart:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparatory phase.
        /// </summary>
        internal static string LabExecutionStatus_PreStart_Title {
            get {
                return ResourceManager.GetString("LabExecutionStatus:PreStart:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This lab is active. You can work on all exercises and submit all flags.&lt;br&gt;End of working time: &lt;strong&gt;{0:g}&lt;/strong&gt;..
        /// </summary>
        internal static string LabExecutionStatus_Start_Text {
            get {
                return ResourceManager.GetString("LabExecutionStatus:Start:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string LabExecutionStatus_Start_Title {
            get {
                return ResourceManager.GetString("LabExecutionStatus:Start:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This lab is not yet enabled. You can neither work on exercises nor submit flags..
        /// </summary>
        internal static string LabExecutionStatus_Undefined_Text {
            get {
                return ResourceManager.GetString("LabExecutionStatus:Undefined:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enabled.
        /// </summary>
        internal static string LabExecutionStatus_Undefined_Title {
            get {
                return ResourceManager.GetString("LabExecutionStatus:Undefined:Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab server.
        /// </summary>
        internal static string LabServer {
            get {
                return ResourceManager.GetString("LabServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory.
        /// </summary>
        internal static string Mandatory {
            get {
                return ResourceManager.GetString("Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not solved.
        /// </summary>
        internal static string NotSolved {
            get {
                return ResourceManager.GetString("NotSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        internal static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solved.
        /// </summary>
        internal static string Solved {
            get {
                return ResourceManager.GetString("Solved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active.
        /// </summary>
        internal static string SwitchLab_Active {
            get {
                return ResourceManager.GetString("SwitchLab:Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hidden.
        /// </summary>
        internal static string SwitchLab_Hidden {
            get {
                return ResourceManager.GetString("SwitchLab:Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to selected lab.
        /// </summary>
        internal static string SwitchLab_Submit {
            get {
                return ResourceManager.GetString("SwitchLab:Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch lab.
        /// </summary>
        internal static string SwitchLab_Title {
            get {
                return ResourceManager.GetString("SwitchLab:Title", resourceCulture);
            }
        }
    }
}
