services:
  ctf4e-server:
    image: ctf4e/ctf4e-server:latest
    volumes:
      - type: bind
        source: ./config-main/appsettings.Production.json
        target: /app/appsettings.Production.json
        read_only: true
    environment:
      # Enable these for HTTPS support
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/config/${CERT_FILE_NAME}
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
    ports:
      - "80:80"
    depends_on:
      - ctf4e-database
  
  ctf4e-database:
    image: library/mariadb:lts
    volumes:
      - type: volume
        source: ctf4e-state
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      
  ctf4e-labserver:
    image: ctf4e/ctf4e-labserver:latest
    volumes:
      - type: bind
        source: ./config-labserver/appsettings.Production.json
        target: /app/appsettings.Production.json
        read_only: true
      - type: bind
        source: ./config-labserver/labconfig.json
        target: /config/labconfig.json
        read_only: false
      - type: volume
        source: ctf4e-labserver-state
        target: /users
    environment:
      # Enable these for HTTPS support
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/config/${CERT_FILE_NAME_LABSERVER}
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD_LABSERVER}
    ports:
      - "8081:80"
    depends_on:
      - ctf4e-database
  
volumes:
  ctf4e-state:
  ctf4e-labserver-state:
