version: "3.2"

services:
  ctf4e-server:
    image: ctf4e/ctf4e-server:latest
    volumes:
      - type: bind
        source: ${CONFIG_DIRECTORY}
        target: /config
    environment:
      - CTF4E_CONFIG_FILE=/config/${CONFIG_FILE_NAME}
      - CTF4E_CERT_FILE=/config/${CERT_FILE_NAME}
      - CTF4E_CERT_PASSWORD=${CERT_PASSWORD}
    ports:
      - "${HOST_PORT}:5000"
    depends_on:
      - ctf4e-database
  
  ctf4e-database:
    image: library/mariadb:latest
    volumes:
      - type: volume
        source: ctf4e-state
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      
  ctf4e-labserver1:
    image: ctf4e/ctf4e-labserver:latest
    volumes:
      - type: bind
        source: ${CONFIG_DIRECTORY}
        target: /config
      - type: volume
        source: ctf4e-labserver1-state
        target: /users
    environment:
      - CTF4E_LAB_CONFIG_FILE=/config/${CONFIG_FILE_NAME_LABSERVER1}
      - CTF4E_LAB_CERT_FILE=/config/${CERT_FILE_NAME_LABSERVER1}
      - CTF4E_LAB_CERT_PASSWORD=${CERT_PASSWORD_LABSERVER1}
    ports:
      - "${HOST_PORT_LABSERVER1}:5001"
    depends_on:
      - ctf4e-database
  
volumes:
  ctf4e-state:
  ctf4e-labserver1-state:
