name: Build & Push Docker image

on:
  push:
    tags:
      - server/*

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # From https://github.community/t/how-to-get-just-the-tag-name/16241/7
    - name: Extract version from tag
      id: get_version
      run: |
        echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/server\//}
        echo ::set-output name=SHORT_HASH::$(git rev-parse --short "$GITHUB_SHA")
    
    - name: Build and push main server docker image
      uses: docker/build-push-action@v1
      with:
        repository: ctf4e/ctf4e-server
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}
        tags: latest,${{ steps.get_version.outputs.VERSION }}
        dockerfile: src/Ctf4e.Server/Dockerfile
        build_args: BUILD_VERSION=${{ steps.get_version.outputs.SHORT_HASH }}
    
    - name: Build and push lab server docker image
      uses: docker/build-push-action@v1
      with:
        repository: ctf4e/ctf4e-labserver
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}
        tags: latest,${{ steps.get_version.outputs.VERSION }}
        dockerfile: src/Ctf4e.LabServer/Dockerfile
        build_args: BUILD_VERSION=${{ steps.get_version.outputs.SHORT_HASH }}