name: Build & Push Docker image

on:
  push:
    tags:
      - server/*

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    # From https://github.community/t/how-to-get-just-the-tag-name/16241/7
    - name: Extract version from tag
      id: get_version
      run: |
        echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/server\//}
    
    - name: Set up builder
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    
    - name: Build and push main server docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ctf4e/ctf4e-server:latest
          ctf4e/ctf4e-server:${{ steps.get_version.outputs.VERSION }}
        file: src/Ctf4e.Server/Dockerfile
        build-args: BUILD_VERSION=${{ steps.get_version.outputs.VERSION }}
    
    - name: Build and push lab server docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ctf4e/ctf4e-labserver:latest
          ctf4e/ctf4e-labserver:${{ steps.get_version.outputs.VERSION }}
        file: src/Ctf4e.LabServer/Dockerfile