name: Build & Push Docker image

on:
  push:
    tags:
      - server/*

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # From https://github.community/t/how-to-get-just-the-tag-name/16241/7
    - name: Extract verson from tag
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/server\//}
    - name: Build and push docker image
      uses: docker/build-push-action@v1
      with:
        repository: janwichelmann/ctf4e
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}
        tags: latest,${{ steps.get_version.outputs.VERSION }}
        dockerfile: src/Ctf4e.Server/Dockerfile
        